### ISSUE TITLE
Incorrect GDAL bindings usage

### ISSUE THREAD

**Issue by MaxRev-Dev** [CodingGeoInfo/Prototyp#1]
Hi, I'm a maintainer of bindings library your project depends on.
Looking through github repos usages for a better understanding how it used by developers.

From your sources:
https://github.com/CodingGeoInfo/Prototyp/blob/7898ecbf2d848316104fde52fa7c7f55728b076f/Prototyp/Elements/RasterData.cs#L226-L232

Please, update usages of bindings according to the documentation. PROJ_PATH and other environmental variables should be set using a static method `Maxrev.Gdal.Core.GdalBase.ConfigureAll()`. This removes several bugs on configuring your app in different environments. There is **NO need to find proj.db manually**, everything is handled by library already. 
You can see the [sources](https://github.com/MaxRev-Dev/gdal.netcore/tree/master/compile) and [documentation](https://github.com/MaxRev-Dev/gdal.netcore#how-to-use) for details.

**Comment by BAGZZlash** [comment]
Fixed, thank you.
